title: Jose Donoso Palomino # your name (or website title) here
logo: "/images/foto_perfil.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst, Madrid, España
  <br><br>
  Mi objetivo es ayudar a las empresas a generar valor a través de los datos, así como seguir aprendiendo y mejorando cada día.
  <br><br>
  Tengo experiencia cómo analista de datos, trabajando con herramientas de ETL así como lenguajes como SQL y Python.
  <br><br>
  <a href="https://www.linkedin.com/in/jose-donoso-palomino//">Entra a mi perfil de LinkedIn</a> 
  <br><br>
  <a href="/pdf/last_cv.pdf">Mira mi Curriculum Vitae (CV) </a> 
  
theme: jekyll-theme-minimal
