title: Jose Donoso Palomino # your name (or website title) here
logo: "/images/foto_perfil.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst, Madrid, España
  <br><br>
  Mi objetivo es ___________
  <br><br>
  Tengo experiencia en ___________
  <br><br>
  <a href="https://www.linkedin.com/in/jose-donoso-palomino//">Entra a mi perfil de LinkedIn</a> 
  <br><br>
  <a href="/pdf/last_cv.pdf">Mira mi Curriculum Vitae (CV) </a> 
  
theme: jekyll-theme-minimal
